export enum NOTE_STATUS {
  NORMAL = 'NORMAL',
  PINNED = 'PINNED',
  ARCHIVED = 'ARCHIVED',
  DELETED = 'DELETED',
}

export enum NOTE_TYPE {
  TEXT = 'TEXT',
  CHECKBOX = 'CHECKBOX',
}

export enum NOTE_BACKGROUND_COLOR {
  DEFAULT = 'DEFAULT',
  CORAL = 'CORAL',
  PEACH = 'PEACH',
  SAND = 'SAND',
  MINT = 'MINT',
  SAGE = 'SAGE',
  FOG = 'FOG',
  STORM = 'STORM',
  DUSK = 'DUSK',
  BLOSSOM = 'BLOSSOM',
  CLAY = 'CLAY',
  CHALK = 'CHALK',
}

export enum NOTE_BACKGROUND_IMAGE {
  DEFAULT = 'DEFAULT',
  GROCERIES = 'GROCERIES',
  FOOD = 'FOOD',
  MUSIC = 'MUSIC',
  RECIPES = 'RECIPES',
  NOTES = 'NOTES',
  PLACES = 'PLACES',
  TRAVEL = 'TRAVEL',
  VIDEO = 'VIDEO',
  CELEBRATION = 'CELEBRATION',
}
